server.port=8085

# Nouvelle URL pour ton projet d'assurance
spring.datasource.url=jdbc:mysql://localhost:3306/assurance_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# Utilise le dialecte moderne pour MySQL 8+ ou laisse Spring le détecter
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect